create table salesmadhu 
(Row_ID	   	number(5) primary key,
Order_ID    	varchar2(15),	
Order_Date  	date,	
Ship_Date   	date, 	
Ship_Mode   	varchar2(25),	
Customer_ID	varchar2(10),
Customer_Name	varchar2(50),
Segments	varchar2(15),
Country	        varchar2(15),
City	        varchar2(25),
States	        varchar2(25),
Postal_Code	varchar2(10),
Region	        varchar2(15),
Product_ID	varchar2(20),
Category	varchar2(25),
Sub_Category	varchar2(25),
Product_Name	varchar2(150),
Sales		number(15,5),
Quantity	number(5),
Discount	number(5,2),
Profit          number(15,5))